#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_4x12(KC_TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLSH, LCS_T(KC_CAPS), KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_MINS, SC_LSPO, LCTL_T(KC_SCLN), KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, RCTL_T(KC_Z), SC_RSPC, LCS(KC_TAB), KC_GRV, LT(2,KC_ESC), KC_LGUI, LALT_T(KC_LBRC), LT(1,KC_ENT), LT(1,KC_SPC), RALT_T(KC_RBRC), KC_RGUI, LT(2,KC_BSLS), KC_BSPC, LCTL(KC_TAB)),
    [1] = LAYOUT_ortho_4x12(KC_NUM, KC_MUTE, KC_VOLD, KC_MPLY, KC_VOLU, KC_PGUP, KC_PAST, KC_P7, KC_P8, KC_P9, KC_PLUS, KC_DEL, KC_HOME, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_END, KC_PSLS, KC_P4, KC_P5, KC_P6, KC_MINS, LCS_T(KC_EQL), SC_LSPO, KC_LCTL, QK_REP, LCTL(KC_LEFT), LCTL(KC_RGHT), KC_PGDN, KC_PSCR, KC_P1, KC_P2, KC_P3, KC_RCTL, SC_RSPC, KC_NO, KC_NO, KC_NO, KC_NO, KC_LALT, LGUI(KC_L), LSG(KC_S), KC_P0, KC_PDOT, KC_ENT, KC_BSPC, KC_NO),
    [2] = LAYOUT_ortho_4x12(KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL, CW_TOGG, KC_F1, KC_F2, KC_F3, KC_F4, QK_REP, QK_AREP, LCG(KC_LEFT), LGUI(KC_TAB), LCG(KC_D), LCG(KC_RGHT), KC_NO, KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, QK_REP, QK_AREP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(4), KC_F9, KC_F10, KC_F11, KC_F12, KC_LALT, KC_RALT, KC_NO, KC_NO, KC_NO, KC_NO, TO(3)),
    [3] = LAYOUT_ortho_4x12(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_I, KC_O, KC_P, KC_BSLS, KC_DEL, LCS_T(KC_CAPS), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, SC_LSPO, LCTL_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, RCTL_T(KC_SLSH), SC_RSPC, LCS(KC_TAB), KC_GRV, LT(2,KC_ESC), KC_LGUI, LALT_T(KC_LBRC), LT(1,KC_ENT), LT(1,KC_SPC), RALT_T(KC_RBRC), KC_RGUI, LT(2,KC_BSLS), KC_BSPC, TO(0)),
    [4] = LAYOUT_ortho_4x12(KC_TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLSH, LCS_T(KC_CAPS), KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_MINS, SC_LSPO, LCTL_T(KC_SCLN), KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_RPRN, LCTL(KC_TAB), KC_BSPC, KC_ESC, KC_LGUI, LALT_T(KC_LBRC), SH_T(KC_SPC), KC_ENT, RALT_T(KC_RBRC), TO(0), KC_BSLS, KC_GRV, LCS(KC_TAB))
};


const keypos_t PROGMEM hand_swap_config[MATRIX_ROWS][MATRIX_COLS] = {
  {{11, 0}, {10, 0}, {9, 0}, {8, 0}, {7, 0}, {6, 0}, {5, 0}, {4, 0}, {3, 0}, {2, 0}, {1, 0}, {0, 0}},
  {{11, 1}, {10, 1}, {9, 1}, {8, 1}, {7, 1}, {6, 1}, {5, 1}, {4, 1}, {3, 1}, {2, 1}, {1, 1}, {0, 1}},
  {{11, 2}, {10, 2}, {9, 2}, {8, 2}, {7, 2}, {6, 2}, {5, 2}, {4, 2}, {3, 2}, {2, 2}, {1, 2}, {0, 2}},
  {{11, 3}, {10, 3}, {9, 3}, {8, 3}, {7, 3}, {6, 3}, {5, 3}, {4, 3}, {3, 3}, {2, 3}, {1, 3}, {0, 3}},
};


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C